// <auto-generated />
using System;
using BarC.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BarC.Migrations
{
    [DbContext(typeof(BarDatabaseContext))]
    [Migration("20200619044034_BarC.Context.BarDatabaseContext")]
    partial class BarCContextBarDatabaseContext
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BarC.Models.Pedido", b =>
                {
                    b.Property<int>("IdNumero")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("UsuarioId");

                    b.HasKey("IdNumero");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Pedido");
                });

            modelBuilder.Entity("BarC.Models.Prod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreProducto");

                    b.Property<double>("Precio");

                    b.HasKey("Id");

                    b.ToTable("Prod");
                });

            modelBuilder.Entity("BarC.Models.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreProducto");

                    b.Property<int>("Pedidofk");

                    b.Property<double>("Precio");

                    b.Property<int>("Productofk");

                    b.HasKey("Id");

                    b.HasIndex("Pedidofk");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("BarC.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido");

                    b.Property<string>("DNI");

                    b.Property<string>("Domicilio");

                    b.Property<int>("Edad");

                    b.Property<string>("Email");

                    b.Property<DateTime>("FechaNacimiento");

                    b.Property<string>("Nombre");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("BarC.Models.Pedido", b =>
                {
                    b.HasOne("BarC.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("BarC.Models.Producto", b =>
                {
                    b.HasOne("BarC.Models.Pedido", "Pedido")
                        .WithMany()
                        .HasForeignKey("Pedidofk")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
